version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181" # Exposing Zookeeper port
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092" # Exposing Kafka port
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost # Advertised hostname for Kafka
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181 # Zookeeper connection string



#zookeeper: This is the name of the service.
#image: wurstmeister/zookeeper: Specifies the Docker image to use for this service. In this case, it's the wurstmeister/zookeeper image.
#container_name: zookeeper: Sets the name of the container to zookeeper.
#ports: Maps port 2181 on the host to port 2181 on the container. This is the default port for Zookeeper.


#kafka: This is the name of the service.
#--------------------------------------
#image: wurstmeister/kafka: Specifies the Docker image to use for this service. In this case, it's the wurstmeister/kafka image.
#container_name: kafka: Sets the name of the container to kafka.
#ports: Maps port 9092 on the host to port 9092 on the container. This is the default port for Kafka.
#environment: Sets environment variables for the Kafka container:
#KAFKA_ADVERTISED_HOST_NAME: localhost: Sets the advertised hostname for Kafka to localhost.
#KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181: Specifies the Zookeeper connection string, pointing to the zookeeper service on port 2181.
#  Summary
#----------
#This docker-compose.yml file sets up two services: Zookeeper and Kafka. Zookeeper is used for managing and coordinating Kafka brokers. Kafka is configured to connect to the Zookeeper service and is set up to run on localhost.



